services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: latex-matrix-calculator-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: latex-matrix-calculator-client
    ports:
      - "3000:80"
